---
ansible_python_interpreter: /usr/bin/python3

validation:
  # Check if OpenNebula services are running
  core_services: true
  # List of services to check enabled, stop and restart
  service_list:
    - name: opennebula.service
      desc: OpenNebula core (oned)
    - name: opennebula-gate.service
      desc: OpenNebula gate
    - name: opennebula-flow.service
      desc: OpenNebula flow
  check_fireedge_ui: false
  run_storage_benchmark: false
  run_ha_verifications: false
  run_network_benchmark: true

  create_vnet: true
  vnet:
    name: 'test-vnet'
    desc: 'A test network for post-deployment cloud verification'
    bridge: 'br-test'
    vn_mad: 'dummy'
    phydev: 'eth1'
    network_address: '192.168.150.100'
    network_mask: '255.255.255.0'
    dns: '8.8.8.8'
    gateway: '192.168.150.1'
    ar:
      - type: "IP4"
        ip: '192.168.150.100'
        size: '10'

  conn_matrix:
    bridge_name: br0
    vnet_name: public

  vm:
    check_connection: false
    market_name: 'Alpine Linux 3.21'
    # template_extra: |
    #   MEMORY="512"
  run_vm_ha: true
  vm_ha:
    produce_error_method: 'if_down'
    if_down_params:
      interface_name: 'br0'

