---
- hosts: "{{ frontend_group | d('frontend') }}"
  tasks:
    # Only execute these steps on a single frontend host
    - when: validation.run_test_vm | default(true) and hostvars[groups[frontend_group | d('frontend')][0]]['ansible_host'] == ansible_host
      block:
      - name: Cleanup test template
        ansible.builtin.shell: |
          onetemplate delete -R {{ test_vm_template_id }}
        register: cleanup_result
        failed_when: "cleanup_result.rc != 0"

      - name: Cleanup test image
        ansible.builtin.shell: |
          oneimage delete {{ test_vm_template_image_id }}
        register: cleanup_result
        failed_when: "cleanup_result.rc != 0 and 'Error getting image' not in cleanup_result.stderr"
        retries: 10
        delay: 10

      - name: Remove /tmp/test_vm_template_extra.txt from remote host
        ansible.builtin.file:
          path: /tmp/test_vm_template_extra.txt
          state: absent
        when: validation.test_vm.vm.template_extra is defined
