---

# Will launch verification framework on the frontends
- hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - role: verification
          
# Run network tests on the hypervisor hosts
- hosts: "{{ node_group | d('node') }}"
  roles:
    - role: verification

